In [14]:
import torch

변수 선언(+데이터 입력)

In [15]:
x=torch.ones(2,2, requires_grad = True)
#x에 대해 미분이 가능하도록 x에 대한 모든 연산을 출력가능

print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


모델 내 연산 예측값 산출

In [16]:
y=x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


손실함수 계산

In [17]:
z=2*y**2

res = z.mean()

손실 산출

In [18]:
print(res)

tensor(8., grad_fn=<MeanBackward0>)


최적화는 손실함수를 바탕으로 미분

In [19]:
# d(res)/dx_i = x_i +1
# res = z_1+...+z_4 / 4
# z_i= 2y_1 **2
#이 모든 과정들이 : 
res.backward()      #이거임


In [20]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [21]:
import torch.nn as nn
import torch.nn.functional as F
#이미 만들어진 라이브러리

