In [ ]:
# torch : the torch package contains data structures for multi-dimmensional tensors
# and mathematical operations over these are defined.

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,4)
print(x)

tensor([[2.4849e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)

tensor([[0.2311, 0.5264, 0.2672, 0.7684, 0.0597, 0.7223],
        [0.1109, 0.6696, 0.7036, 0.6156, 0.4248, 0.2832],
        [0.7598, 0.0409, 0.8825, 0.0132, 0.0681, 0.4011],
        [0.4842, 0.0182, 0.0029, 0.3349, 0.7459, 0.7776],
        [0.8157, 0.1763, 0.1099, 0.2509, 0.2853, 0.1663]])

In [7]:
l=[13,4]
r=np.array([4,56,7])

In [8]:
torch.tensor(l)

tensor([13,  4])

In [9]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [10]:
x.size()

torch.Size([5, 4])

In [11]:
type(x)

torch.Tensor

In [12]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.9096, 0.8932],
        [0.7959, 0.7360]])
tensor([[0.6131, 0.0345],
        [0.1690, 0.4881]])


In [13]:
x+y

tensor([[1.5227, 0.9277],
        [0.9649, 1.2240]])

In [14]:
torch.add(x,y)

tensor([[1.5227, 0.9277],
        [0.9649, 1.2240]])

In [15]:
y.add(x)
#y의 값을 변화시키지 않음

tensor([[1.5227, 0.9277],
        [0.9649, 1.2240]])

In [16]:
y

tensor([[0.6131, 0.0345],
        [0.1690, 0.4881]])

In [17]:
y.add_(x)
#_는 y의 값을 변화시킴

tensor([[1.5227, 0.9277],
        [0.9649, 1.2240]])

In [18]:
y

tensor([[1.5227, 0.9277],
        [0.9649, 1.2240]])

indexing

In [19]:
y[1,1]

tensor(1.2240)

In [20]:
y[:,1]

tensor([0.9277, 1.2240])

In [21]:
x = torch.rand(8,8)
#8x8 x 생성

view()는 cnn에서 convolusion layer에서 FC로 정렬할 때

In [22]:
x.view(64)
#8x8로 생성된 x를 열기준으로 나열


tensor([0.7928, 0.8559, 0.7847, 0.5087, 0.6242, 0.4927, 0.4595, 0.8799, 0.9088,
        0.2875, 0.3367, 0.3700, 0.9355, 0.4052, 0.0757, 0.9677, 0.9050, 0.4717,
        0.0575, 0.3437, 0.6052, 0.5589, 0.7913, 0.5200, 0.3168, 0.0316, 0.4038,
        0.5787, 0.3478, 0.3227, 0.6613, 0.3438, 0.0175, 0.4669, 0.8884, 0.2511,
        0.8068, 0.7515, 0.8862, 0.0526, 0.0333, 0.8875, 0.6090, 0.7658, 0.2151,
        0.9750, 0.7764, 0.9185, 0.8491, 0.3679, 0.6005, 0.1102, 0.3341, 0.0890,
        0.2357, 0.9977, 0.3551, 0.4995, 0.6675, 0.9450, 0.7727, 0.0946, 0.6849,
        0.1731])

In [23]:
x.view(4,16)
#x를 4x16으로 나열

tensor([[0.7928, 0.8559, 0.7847, 0.5087, 0.6242, 0.4927, 0.4595, 0.8799, 0.9088,
         0.2875, 0.3367, 0.3700, 0.9355, 0.4052, 0.0757, 0.9677],
        [0.9050, 0.4717, 0.0575, 0.3437, 0.6052, 0.5589, 0.7913, 0.5200, 0.3168,
         0.0316, 0.4038, 0.5787, 0.3478, 0.3227, 0.6613, 0.3438],
        [0.0175, 0.4669, 0.8884, 0.2511, 0.8068, 0.7515, 0.8862, 0.0526, 0.0333,
         0.8875, 0.6090, 0.7658, 0.2151, 0.9750, 0.7764, 0.9185],
        [0.8491, 0.3679, 0.6005, 0.1102, 0.3341, 0.0890, 0.2357, 0.9977, 0.3551,
         0.4995, 0.6675, 0.9450, 0.7727, 0.0946, 0.6849, 0.1731]])

In [24]:
x.view(-1, 16)
#알아서 dimension 계산

tensor([[0.7928, 0.8559, 0.7847, 0.5087, 0.6242, 0.4927, 0.4595, 0.8799, 0.9088,
         0.2875, 0.3367, 0.3700, 0.9355, 0.4052, 0.0757, 0.9677],
        [0.9050, 0.4717, 0.0575, 0.3437, 0.6052, 0.5589, 0.7913, 0.5200, 0.3168,
         0.0316, 0.4038, 0.5787, 0.3478, 0.3227, 0.6613, 0.3438],
        [0.0175, 0.4669, 0.8884, 0.2511, 0.8068, 0.7515, 0.8862, 0.0526, 0.0333,
         0.8875, 0.6090, 0.7658, 0.2151, 0.9750, 0.7764, 0.9185],
        [0.8491, 0.3679, 0.6005, 0.1102, 0.3341, 0.0890, 0.2357, 0.9977, 0.3551,
         0.4995, 0.6675, 0.9450, 0.7727, 0.0946, 0.6849, 0.1731]])

tensor to numpy

In [26]:
y=x.numpy()
print(y)

[[0.7928269  0.85587573 0.7846527  0.5087313  0.6241981  0.49274766
  0.4594803  0.8799002 ]
 [0.9087665  0.2874512  0.33668518 0.36998665 0.9355469  0.4052257
  0.07573217 0.9676559 ]
 [0.9049812  0.4717077  0.05747712 0.34372056 0.6052417  0.5588846
  0.7912799  0.5200025 ]
 [0.31682646 0.03158253 0.40382946 0.57872456 0.34775132 0.32269233
  0.6612542  0.34384543]
 [0.01750189 0.46687883 0.88835603 0.25110304 0.8067659  0.7514553
  0.8862191  0.05263519]
 [0.03334761 0.88754296 0.60896385 0.76583046 0.21509516 0.9750142
  0.7763899  0.9185047 ]
 [0.84913194 0.3679496  0.60051113 0.11016554 0.334063   0.08897871
  0.23572445 0.99773467]
 [0.35513663 0.49949247 0.66754115 0.94504404 0.77274173 0.09463102
  0.68489903 0.17311323]]


In [27]:
type(y)

numpy.ndarray

In [28]:
x=torch.ones(1)

In [29]:
x
#x는 1이 아닌 tensor 값으로 저장됨

tensor([1.])

In [30]:
x.item()
#tensor 값으로 저장된 x를 값으로 변환
#loss function을 floating하거나 직접 출력하고 싶을때

1.0