# 1.

행렬과 매트릭스를 코드로 표현하는 방식

코드를 방정식으로 표현한다면?

In [ ]:
coefficient_matrix = [[2,2,1],[2,-1,2],[1,-1,2]]
constant_vector = [9,6,5]



numpy

- maxtix, vector 연산
- list보다 빠르고 메모리 효율
- 반복문 없이 데이터 배열에 대한 처리 지원
- 선형대수
- c, c++  등의 언어와 통합 가능

In [ ]:
#가상환경 설치
# conda create -n upstage python =3.8
# conda activate upstage
# conda install numpy
# conda install jupyter


ndarray

- numpy는 np.array 함수를 활용 하여 배열 생성
- 하나의 데이터 type만 배열에 넣을 수 있음
- list와의 차이는 dynamic typing not supported

In [1]:
import numpy as np

# array creation
test_array = np.array([1,4,5,8], float)
print(test_array)

type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [ ]:
a = [1,23,4,5,6]
b = [5,4,3,2,1]

a = np.array(a,int)

In [4]:
# 여러 타입이 들어와도 하나로 통일됨
t = np.array(['1','4',5.0,8], float)
type(t[1])


numpy.float64

numpy와 list의 차이
- numpy : 데이터가 메모리에 차례대로 할당됨 + 메모리의 크기가 일정
- list : 메모리의 static한 공간에 할당됨(각각의 주소값이 들어감)

--> numpy의 연산이 더 효율적인 이유

In [5]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

# list는 주소값이 같기 때문에 True
a[0] is b[-1]

True

In [6]:
a = np.array(a)
b = np.array(b)

# numpy는 다른 주소값을 가지기 때문에 False
a[0] is b[-1]

False

shape : dimension 구성 반환

dtype : array의 데이터 type을 반환

In [7]:
test_array = np.array([1,2,3,4,5,6], float)

test_array.dtype

dtype('float64')

In [9]:

a = [[1,2,3],[4,5,6],[4,5,6]]

np.array(a).shape

(3, 3)

In [12]:
# scalar
a = [3]

np.array(a,int).shape     # (column,)

(1,)

In [14]:
a = [[1,2],[3,4]]

np.array(a,int).shape   #

(2, 2)

In [10]:
#maxtix
matrix = [[1,2,3,5],
          [1,2,5,7],
          [1,2,5,8]]
np.array(matrix, int).shape       # (row,column)

(3, 4)

In [16]:
# tensor

tensor = [[ [1,2,5,8],[1,2,52,58],[1,2,52,58] ],
          [[1,2,52,58],[1,2,52,58],[1,2,52,58]],
          [[1,2,52,58],[1,2,52,58],[1,2,52,58]],
          [[1,2,52,58],[1,2,52,58],[1,2,52,58]]]

np.array(tensor,int).shape    # (channel_dimension, row,column)

(4, 3, 4)

- ndim = number of dimensions
- size : data의 개수(element)

In [24]:
# 한가지의 데이터만 저장 가능
np.array([[1,2,3],[4.5,5,6]], dtype = np.int8)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

nbytes : ndarray object의 메모리 크기 반환

In [23]:
np.array([[1,2,3],[4.5,5,6]], dtype = np.float64).nbytes      # 64bits == 8bytes * 6 = 48

np.array([[1,2,3],[4.5,5,6]], dtype = np.int8).nbytes     # 8bits = 1bytes * 6 = 6

np.array([[1,2,3],[4.5,5,6]], dtype = np.float32).nbytes  # 32bits == 4bytes *6 = 24

24

# 2. Handling shape

reshape : Array의 shape 크기 변경, element의 크기는 동일

In [31]:
test = np.array([[1,2,3,4],[7,4.5,5,6]], dtype = np.float64)
np.array(test).shape

(2, 4)

In [33]:
np.array(test).reshape(8,)

array([1. , 2. , 3. , 4. , 7. , 4.5, 5. , 6. ])

In [35]:
np.array(test).reshape(8,).shape

(8,)

In [36]:
#reshape (-1) : size를 기반으로 row 개수 자동수정
np.array(test).reshape(-1,2).shape

(4, 2)

In [38]:
np.array(test).reshape(-1,2,2).shape

(2, 2, 2)

flatten : 다차원 array를 1차원으로 변환

In [50]:
np.array(test).flatten().shape

(8,)

## indexing & slicing

- 이차원 배열에서 [0,0] 표기법
- matrix일 경우 [row,col]

In [56]:
a = np.array([[1,2,3],[4,5,6]], int)

print(a)
print(a[0,0])

#변경 가능
a[0,0] = 12
a[1][2] = 100
a

[[1 2 3]
 [4 5 6]]
1


array([[ 12,   2,   3],
       [  4,   5, 100]])

- list와 달리 행과 열 부분을 나눠서 slicing 가능
- matrix의 부분 집합을 추출

In [62]:
a = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)

print(a[:, 2:])    #모든 row, col은 2번째 부터
print(a[1, 1:3])   # row1, col 1 to 2
print(a[1:3])      # row 1 to 2 , all col

print(a[:, 2:])
a[:, 1:3].shape

[[5 8]
 [5 8]
 [5 8]
 [5 8]]
[2 5]
[[1 2 5 8]
 [1 2 5 8]]
[[5 8]
 [5 8]
 [5 8]
 [5 8]]


(4, 2)

slicing for numpy array

In [63]:
a = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]],int)

a[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [64]:
a[::2, ::3]

array([[ 0,  3],
       [10, 13]])

## creation function

arange
- 범위를 지정, 값의 list를 생성
- arange(시작, 끝, 범위)

In [66]:
np.arange(30)

np.arange(0,30,0.5)   # float이 가능

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])

In [67]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

ones, zeros, and empty

- ones : 1로 채움
- zeros : 0으로 채움
- empty : 비움

In [72]:
#zeros
np.zeros(shape=(10,), dtype = np.int8)

#ones
np.ones(shape=(10,), dtype = np.int8)

#empty

np.empty(shape=(10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [73]:
np.empty((3,5))

array([[4.78883162e-310, 0.00000000e+000, 3.32480434e-114,
        8.77581965e-095, 6.01346953e-154],
       [6.01347002e-154, 1.50597083e+161, 1.71957665e+238,
        3.32480434e-114, 1.87300511e-152],
       [8.87297278e+247, 8.41444044e+276, 1.69375270e+190,
        6.93510668e-310, 7.11454530e-322]])

something_like

- 기존 ndarray의 shape 크기만큼 1,0 empty array 반환

In [75]:
test = np.arange(30).reshape(5,6)
np.ones_like(test)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## eye, identity, digonal

In [81]:
# 1. 단위 행렬

np.identity(n=3, dtype=np.int8)
np.identity(3)


array([1, 5])

In [ ]:
# 2. eye : 대각선이 1인 행렬, k값의 시작 index의 변경 가능
np.eye(3)

np.eye(3, k=2)

In [83]:
# 3.diag : 대각 행렬의 값 추출

matrix = np.arange(9).reshape(-1,3)
print(matrix)

np.diag(matrix, k=0)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

## random sampling

- uniform : 균등
- normal : 정규
- exponential

In [84]:
np.random.uniform(0,1,10).reshape(2,5)    # 균등분포

array([[0.35341686, 0.04436439, 0.36441256, 0.00997998, 0.64550965],
       [0.17002754, 0.53121471, 0.62701854, 0.53827514, 0.58552539]])

In [85]:
np.random.normal(0,1,10).reshape(2,5)   # 정규분포

array([[-0.76267062,  0.7757601 ,  0.93282516,  1.09532594, -0.0300055 ],
       [ 1.6620125 ,  0.05539448,  1.36176104,  0.42855686, -1.26671164]])

In [86]:
np.random.exponential(scale=2, size=100)

array([7.56403284e+00, 1.75352322e+00, 4.63534889e+00, 4.14549845e+00,
       4.89430166e-01, 3.46463930e+00, 8.01565349e-01, 1.63645973e+00,
       1.15190967e+00, 3.54977561e+00, 1.45412226e+00, 2.69785545e-01,
       5.48826534e-01, 2.25788938e+00, 1.03372532e+00, 9.52550153e-01,
       3.69984112e+00, 4.01831494e-01, 1.64337723e-01, 6.33190558e-01,
       1.03795063e+00, 5.61626737e-01, 3.82419808e+00, 2.32806098e+00,
       5.01112522e+00, 2.23621270e+00, 1.75095326e+00, 2.49074961e-01,
       1.95758920e+00, 2.90566541e+00, 1.81086684e+00, 1.32393769e+00,
       2.23582938e+00, 2.03875359e+00, 2.78602308e+00, 5.41813450e+00,
       3.60998675e+00, 9.20498630e-01, 5.81403426e+00, 5.03352226e+00,
       3.83930731e+00, 2.23872718e+00, 1.97170517e+00, 9.95627457e-01,
       4.62504194e+00, 4.15998199e-01, 1.62081715e+00, 2.93971585e+00,
       1.36392600e+00, 4.95105614e-01, 1.02164223e+00, 1.48961554e-02,
       4.15697811e+00, 4.45744131e-01, 4.22198193e-01, 3.61289353e+00,
      

## operation functions

sum

- 각 element들 간의 합

In [89]:
test = np.arange(15).reshape(5,3)
print(test)
np.sum(test)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


105

In [92]:
np.sum(test, dtype=np.float64)

105.0

axis

- 모든 operation function을 실행할 때 기준이 되는 dimension 축

- axis = 1 : row 기준
- axis = 0 : col 기준

In [96]:
test = np.arange(1,13).reshape(3,4)
print(test)

print(test.sum(axis=1))

print(test.sum(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[15 18 21 24]


mean

- 평균

In [99]:
test.mean()

print(test.mean(axis=0))
print(test.mean(axis=1))

[5. 6. 7. 8.]
[ 2.5  6.5 10.5]


std
- 표준편차

In [100]:
test.std()

print(test.std(axis=0))
print(test.std(axis=1))

[3.26598632 3.26598632 3.26598632 3.26598632]
[1.11803399 1.11803399 1.11803399]


## concatenate

- numpy array끼리 붙이는 함수

- vstack : row기준
- hstack : col기준

In [101]:
# vstack

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
# hstack
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [104]:
# concatenate

a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate( (a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
a = np.array([[1,2],
              [3,4]
              ])

b = np.array([[7,8]])

print(np.concatenate( (a,b), axis=0))

print(np.concatenate( (a,b.T), axis=1))     # transpose를 해줘야 연산이 맞음


[[1 2]
 [3 4]
 [7 8]]
[[1 2 7]
 [3 4 8]]


축을 새로 만들고 싶으면
- np.newaxis

In [114]:
b = np.array([5,6])
print(b.shape)

b = b[np.newaxis, :]
print(b.shape)

(2,)
(1, 2)


## operations

- 기본적인 array간 사칙연산 지원

In [116]:
t = np.array([[1,2,3],[4,5,6]],float)

t + t

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

elementwise operations
- array간 shape이 같을 때 각 element끼리 곱셈

In [117]:
t * t

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

## Dot product
- 곱셈 연산

In [118]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)      # or b의 shape을 (2,3) 한 후 a.dot(b.T)

a.dot(b)

array([[ 58,  64],
       [139, 154]])

Transpose

In [119]:
a = np.arange(1,7).reshape(2,3)
print(a)

print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Broadcasting

- shape이 다른 배열 간 연산 지원

- Scalar - vector 이외에도 vector - matrix 연산도 지원

In [120]:
matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

matrix + scalar     # matrix의 모든 element에 scalar를 더함

array([[4., 5., 6.],
       [7., 8., 9.]])

timeit
- jupyter에서 코드의 퍼포먼스 체크 하는 함수

- 일반적 속도는 : for loop < list < numpy

- 10000000번의 loop에서 약 4배의 성능 차이
- numpy는 c로 구현되어 성능 > dynamic typing
- 대용량 계산에서 흔히 사용
- concatenate처럼 계산이 아닌 할당에서는 속도 차이가 존재하지 않음

In [122]:
def scalar_vector_product(scalar,vector) :
  result = []
  for value in vector :
    result.append(scalar * value)

  return result

iteration_max = 1000000

vector = list(range(iteration_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector)
%timeit [scalar * value for value in range(iteration_max)]
%timeit np.arange(iteration_max)*  scalar

228 ms ± 29.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
132 ms ± 34.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.29 ms ± 241 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# 3

## Comparison

- All
- Any

In [123]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a < 4     # 각각에 대해 진행
a < 1
np.all(a<4)   # 전부가 해당하는가?

np.any(a<4)   # 어느 하나라도 해당하는가?

True

numpy는 배열의 크기가 동일 때 element간 비교의 결과를 boolean으로 반환

In [131]:
a = np.array([1,3,0], float)
b = np.array([5,2,1], float)

print(a > b)
print(b > a)

print( a== b)

(a > b).any()


[False  True False]
[ True False  True]
[False False False]


True

logical boolean
- boolean 조건의 condition

In [132]:
a = np.array([1,3,0], float)

np.logical_and(a > 0, a< 3)

array([ True, False, False])

In [133]:
b = np.array([True,False,False], bool)
np.logical_not(b)

array([False,  True,  True])

## np.where

- np.where(condition,True,False)

In [134]:
np.where(a > 0, 3,2)

array([3, 3, 2])

In [135]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [136]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [137]:
np.isfinite(a)

array([ True, False, False])

## argmax, argmin
- array내 최댓값 또는 최솟값의 index 반환

In [138]:
a = np.array([1,2,3,4,5,6,7,8])
np.argmax(a)

7

In [139]:
np.argmin(a)

0

axis 기준으로 반환

In [142]:
a = np.array([[1,2,4,7],[9,88,6,64],[9,76,3,4]])
print(a)
np.argmax(a, axis=1)      # 각각의 row기준 최대값


[[ 1  2  4  7]
 [ 9 88  6 64]
 [ 9 76  3  4]]


array([3, 1, 1])

In [141]:
np.argmin(a, axis=0)      #각각의 col기준 최솟값

array([0, 0, 2, 2])

## boolean index

- 특정 조건에 따른 값을 배열 형태로 추출
- comparison operation 함수 모두 사용가능

In [143]:
t = np.array([1,4,0,2,3,8,9,7], float)
t > 3

array([False,  True, False, False, False,  True,  True,  True])

In [144]:
t[t>3]

array([4., 8., 9., 7.])

In [145]:
condition = t < 3

t[condition]

array([1., 0., 2.])

fnacy index

- numpy 는 array를 index value로 사용해서 값 추출

In [146]:
a = np.array([2,4,6,8], float)
b= np.array([0,0,1,3,2,1], int)

a[b]    # b배열의 값을 a의 index로 사용

array([2., 2., 4., 8., 6., 4.])

In [147]:
a.take(b)   # bracket과 같음

array([2., 2., 4., 8., 6., 4.])

In [149]:
# matrix 형태도 가능
a = np.array([[1,4,],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

## numpy_data i/o



loadtxt & savetxt
- text의 데이터를 읽고 저장

In [ ]:
a = np.loadtxt('~~.txt')
a

In [ ]:
# int로 변환
a_int = a.astype(int)
a_int2 = a_int[:3]

In [ ]:
np.savetxt('~~.txt', a_int2, delimiter = ',')    # delimiter : 자르는 기준

numpy object - npy

In [ ]:
np.save('~~', arr=a_int2)   # 일반적으로 pickle의 형태로 저장됨

In [ ]:
a_test = np.upload(file= ' ~~.npy')

In [ ]:
npy_array = np.load(file='~~.npy')