# Vector

- 숫자를 원소로 갖는 리스트 혹은 배열

In [3]:
import numpy as np

x = [1,7,2]

x = np.array(x, int)
x

array([1, 7, 2])

In [4]:
x.T

array([1, 7, 2])

- 벡터는 공간에서의 한 점
- 원점으로부터의 상대적 위치
- 벡터에 숫자를 곱하면 길이만 변화(방향은 변화하지 않음)
  - 이를 스칼라곱이라고함

In [6]:
a= np.array([1,2,3])
3*a

array([3, 6, 9])

- 벡터끼리 같은 모양을 가지면 뎃셈 및 뺄셈가능

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b



array([5, 7, 9])

벡터끼리 같은 모양을 가지면 성분곱(Hadamard product, element-wise product) 가능

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a * b

array([ 4, 10, 18])

## 벡터의 덧셈 및 뺄셈

- 두 벡터의 덧셈 및 뺄셈은 __다른 벡터__로부터 상대적 위치이동

In [10]:
a = np.array([1,2])
b = np.array([3,4])

a+b

array([4, 6])

## Norm

- 원점에서부터의 거리
- 벡터의 노름은 임의의 차원  d에 대해 성립함

L1 Norm(맨헤튼 노름)

- Lp=(n∑i|xi|p)1p

- 각 성분의 변화량의 절댓값을 모두 더한 노름



2. L2 Norm(유클리드 노름)

- L2=⎷n∑ix2i
- 피타고라스 정리를 이용한 유클리드 거리

x =[1,2,3,4,5]||x||2=
√(|1|2+|2|2+|3|2+|4|2+|5|2)

=√1+4+9+16+25=√55=7.4161

In [ ]:
# L1 Norm

def l1_norm(x) :
  x_norm = np.abs(x)      # 절대값을 취한 후
  x_norm = np.sum(x_norm)   # 절댓값을 모두 더한 후
  return x_norm   # 반환


def l2_norm(x) :
  x_norm = x^2    # 제곱을 반환
  x_norm = np,sum(x_norm)   # 모두 더하기
  x_norm = np.sqrt(x_norm)  # 루트값을 취한후
  return x_norm   # 반환

# L2는 np.linalg.norm을 이용해도 구현 가능

L1과 L2의 차이

1. L1
  - 노름 상의 원 : 마름모 형태
  - robust, lasso 회귀에 주로 사용
2. L2
  - 노름 상의 원 : 원
  - laplace 근사, ridge 회귀에 주로 사용

두 벡터 사이의 거리를 구하기

- L1,L2 노름을 이용하여 거리를 구할 수 있음
- 두 벡터 사이의 거리를 계산할 때는 벡터의 뺼셈 사용
- 뺄셈을 거꾸로 해도 거리는 같다
- 두 벡터 사이의 각도는 L2노름에서 가능(코사인2법칙)
- 분자 계산 : 내적
- 임의의 d차원에서 이루어지는 행위

In [ ]:
def angle(x,y) :
  v = np.inner(x,y) / (l2_norm(x) * (l2_norm(y)))
  theta = np.arccos(v)
  return theta

정사영

- orthogonal projection
- Proj(x)는 벡터 y로 정사영된 벡터 x의 그림자의 길이
- Proj(x)의 길이는 코사인법칙에 의해 ||x|| cos theta

- 내적은 정사영의 길이를 벡터 y의 길이 ||y||만큼 조정한 값
- 내적은 두 벡터의 유사도를 측정하는데 사용

