Matrix
- 벡터를 원소로 갖는 2차원 배열
-

In [ ]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])



#행렬의 이해

- 벡터가 공간에서의 한 점 이라면 행렬은 여러 점들로 구성됨
- 행렬의 행벡터 xi는 i번째 데이터를 의미
- 행렬의 xij는 i번째 데이터의 j번째 변수의 값

## 행렬의 덧셈, 뺄셈, 성분곱, 스칼라곱

- 행렬은 벡터를 원소로 갖는 2차원 배열
- 행렬낄 같은 모양을 가지면 덧셈, 뺄셈
- 성분곱은 벡터와 같다
  - 각 인덱스의 위치끼리 곱셈
- 스칼라곱도 벡터와 차이가 없다.


행렬의 곱셈

- i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬

- Xij * Yjk
  - 행렬곱은 X의 열의 개수와 Y의 행의 개수가 같아야 한다

In [2]:
import numpy as np

x = np.array([[1,-2,3],
              [7,5,0],
              [-2,-1,2]])

y = np.array([[0,1],
              [1,-1],
              [-2,1]])

x @ y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

- numpy의 np.inner는 i번째 행벡터와 j번째 행벡터 사이의 내적을 성분으로 갖는 행렬을 계산
- 수학의 내적과는 다름
  - 수학에서는 보통 tr(XY.T)를 내적으로 계산
  - 따라서 np.inner를 사용하고 싶으면 Y.T와 해주는 것이?



In [5]:
x = np.array([[1,-2,3],
              [7,5,0],
              [-2,-1,2]])

y = np.array([[0,1],
              [1,-1],
              [-2,1]])

# np.inner(x,y)     # 에러가 뜬다

np.inner(x,y.T) #이렇게 해주면 해결

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

## 행렬은 벡터공간에서 사용되는 연산자로 이해

- 행렬곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있다
- Z = AX 일때
  - 행렬 A를 이용하여 두 벡터 Z,X를 연결하는 개념

- 이를 이용하여 패턴을 추출, 데이터를 압축할 수 있다
  - 모든 선형변환은 행렬곱으로 계산 가능


역행렬
- 어떤 행렬 A의 연산을 거꾸로 되돌리는 행렬
- 역행렬은 행과 열 숫자가 같고 __행렬식이 0이 아닌 경우__에서 계산 가능
  - 역행렬 연산은 n=m일 때만 가능
  - 이 때 행렬 A의 행렬식이 0이 되면 안됨

- linalg 라이브러리를 이용하여 계산가능

In [6]:
x = np.array([[1,-2,3],
              [7,5,0],
              [-2,-1,2]])

np.linalg.inv(x)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [7]:
x @ np.linalg.inv(x)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

- 만약 역행렬을 계산할 수 없다면 유사역행렬 또는 무어-펜로즈 역행렬 A+를 이용

- n>=m : A+ = (A.T @ A)inv @ A.T
- n<=m : A+ = A.T @ (A @ A.T)inv
  - n>=m 이면 A+ @ A = I가 성립
  - n<=m 이면 A @ A+ = I가 성립

In [9]:
y = np.array([[0,1],
              [1,-1],
              [-2,1]])

In [10]:
# pinv() : 유사 역행렬 계산
np.linalg.pinv(y)

array([[ 5.00000000e-01,  4.09730229e-17, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [11]:
np.linalg.pinv(y) @ y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

연립방정식 풀기

- 유사역행렬을 사용하면 무수히 많은 해 중 하나를 찾을 수 있다
  - n<=m인 경우 : 식이 변수의 개수보다 작거나 같은 경우
  - 이 경우 무어-펜로즈 역행렬을 사용


선형회귀분석
- np.linalg.pinv를 이용하면 데이터를 선형모델로 해석하는 선형회귀식을 찾을 수 있음

- n>=m인 경우 : 데이터가 변수의 개수보다 많거나 같은 경우
  - 선형회귀분석은 X와 y가 주어진 상황에서 계수 B를 찾아야함
  - 선형회귀분석은 행이 더 큼으로 방정식을 풀 수 없음
  - B는 데이터를 최대한 잘 표현할 수 있는 선을 의미
  - 이 경우 무어-펜로즈 역행렬을 이용하면 yhat을 찾을 수 있음

- 무어 펜로즈 역행렬의 식
  - B = X+@y  : L2 노름을 최소화시키는 것이 목적
    
    = (X.T @ X)inv @ X.T @ y

In [ ]:
# scikit learn
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

y_test = model.predict(x_test)

# moore-penrose
x_ = np.array([np.append(x,[1]) for x in x])    # intercept항을 직접 추가해야함
beta = np.linalg.pinv(x) @ y
y_test = np.append(x_test) @ beta